apiVersion: v1
kind: ServiceAccount
metadata:
  name: carbon-scheduler-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: carbon-scheduler-role
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["bindings", "pods/binding"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: carbon-scheduler-binding
subjects:
- kind: ServiceAccount
  name: carbon-scheduler-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: carbon-scheduler-role
  apiGroup: rbac.authorization.k8s.io